---
- hosts: 127.0.0.1
  connection: local
  roles:
    - role: conductor
      tags: ["conductor"]
      vars: 
        - step: "destroy"

    - role: kolla
      tags: ["kolla"]
      vars: 
        - step: "destroy"

    - role: repository
      tags: ["repository"]
      vars: 
        - step: "destroy"
