---
# 本地源备份和配置放到config.yml来做，后期优化可以跳过下载已存在的软件包,这边还需要disable本地的myrepo
- name: Download packages for the local yum repository
  shell: yum install -y --downloadonly --downloaddir={{ yum_repository_directory }} {{ item }}
  with_items:
    - "{{ packages }}"
    - "{{ custom_packages | default([])}}"

- name: Download packages for the local pip repository
  shell: pip wheel --timeout 120 --wheel-dir {{ pip_repository_directory }} --find-links {{ pip_repository_directory }} --build /tmp/openstack-builder --log /var/log/repo/repo_builder.log  {{ item }}
  with_items:
    - "{{ requirements }}"
    - "{{ custom_requirements | default([])}}"

# 为源创建软件包索引
- name: Create a package index for the local repository
  block:
    - shell: createrepo {{ item }}
      with_items: "{{ yum_repository_directory }}"
    
    - shell: dir2pi {{ item }}
      with_items: "{{ pip_repository_directory }}"
      notify:
        - Restart nginx service

# 删除原有的repo
- name: Remove primary repo
  shell: rm -rf /etc/yum.repos.d/*

# 拷贝my.repo
- name: Generate the local yum repository
  template:
    src: "{{ role_path }}/templates/my.repo.j2"
    dest: "/etc/yum.repos.d/my.repo"
