---
# 备份主机的yum源目录
- name: Ensure yum.repos.d.bak exist
  file:
    path: /etc/yum.repos.d.bak/
    state: directory

- name: Backup host repository
  copy: src=/etc/yum.repos.d/   dest=/etc/yum.repos.d.bak/

# 重新配置主机的yum源目录，将files里的repo拷贝到yum源目录，后面还可能要安装openstack源，这个后面再做
- name: Reconfigure host repository
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/"
  with_items:
    - CentOS-Base.repo
    - nginx.repo
    - docker.repo

- name: Install epel-release
  yum:
    name: epel-release
    state: latest

# 安装软件源构建工具
- name: Install the local yum repository builder
  yum:
    name: ['nginx', 'gcc', 'git', 'docker-engine', 'createrepo', 'python-pip', 'python-devel', 'libevent-devel']
    state: latest
  notify:
    - Restart nginx service

- name: Install the local pip repository builder
  pip:
    name: ['pip2pi', 'wheel', 'docker-py']
    state: latest

# 设置nginx 开机启动
- name: Enable nginx service
  service: name=nginx enabled=yes

# 检测本地源目录是否存在
- name: Ensure local repository directories exist
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ yum_repository_directory }}"
    - "{{ pip_repository_directory }}"
