---
- name: create dir yum.bak 
  file: 
    path: /etc/yum.bak
    state: directory

- name: backup yum.repo
  copy: src=/etc/yum.repos.d/ dest=/etc/yum.bak/

- name: remove all yum.repo
  shell: rm -rf /etc/yum.repos.d/*

- name: exchange aliyun.repo
  template:
     src: "{{ role_path }}/templates/CentOS-Base.repo.j2"
     dest: "/etc/yum.repos.d/CentOS-Base.repo"

- name: create nginx repo
  shell: |-
    sed 's/^ //' <<" EOF" | tee /etc/yum.repos.d/nginx.repo
    [nginx]
    name=nginx repo
    baseurl=http://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck=0
    enabled=1
    EOF

- name: install nginx and createrepo service
  yum: 
    name: "{{ packages }}"
    state: latest
  vars:
    packages: 
    - nginx
    - createrepo
  notify:
    - restart nginx service

- name: Ensure RPMS directory exists
  file: 
    path: /usr/share/nginx/html/RPMS/
    state: directory

- name: download rpms needed
  shell: yum install -y --downloadonly --downloaddir=/usr/share/nginx/html/RPMS {{ item }}
  with_items:
    - {{ rpm_must_needed }}

- name: create repo
  shell: createrepo /usr/share/nginx/html/RPMS/

- name: create local repo
  block:
    - shell: rm -rf /etc/yum.repos.d/*
    
    - template: 
        src: "{{ role_path }}/templates/my.repo.j2"
        dest: "/etc/yum.repos.d/my.repo"
