---
# yum源目录
yum_repository_directory: "/usr/share/nginx/html/yum"

# pip源目录
pip_repository_directory: "/usr/share/nginx/html/pip"

# 构建环境所需的Python软件包
requirements:
  - docker-py>=1.8.1
  - six>=1.9.0

# 用户自定义安装的Python软件包
custom_requirements:
  -

# 构建环境所需的软件包
packages:
  - nginx
  - docker-engine
  - gcc

# 用户自定义安装的软件包
custom_packages:
  - tcpdump
  - vim
  - git

