---
- block: 
  - name: Prompt
    pause:
      prompt: "Enter your github password"
    register: githubpassword

# 创建 docker.service.d 目录
- name: Ensure docker.service.d exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_service_directory }}"

# 修改docker服务启动项
- name: Modify kolla.conf
  template:
    src: "kolla.conf.j2" 
    dest: "{{ docker_service_directory }}/kolla.conf"

- name: Enabled and restart docker
  service: name=docker enabled=yes state=reloaded

# 安装virtualenv 
- name: Install virtualenv
  pip:
    name: virtualenv
    state: present
    extra_args: --index-url http://{{ inventory_hostname  }}/pip/simple --trusted-host {{ inventory_hostname }}

# Before git clone kolla , ssh-key must be added to github
- name: Git clone kolla from github
  git:
    repo: https://{{ githubuser | urlencode }}:{{ githubpassword.user_input | urlencode | regex_replace('/', '%2F') | regex_replace('@', '%40') }}@github.com/{{ githubuser }}/kolla.git
    dest: /root/kolla
    version: "{{ kolla_branch }}"
    clone: yes

# git clone gather-agent
- name: Git clone gather-agent form github
  git:
    repo: https://{{ githubuser | urlencode }}:{{ githubpassword.user_input | urlencode | regex_replace('/', '%2F') | regex_replace('@', '%40') }}@github.com/{{ githubuser }}/gather-agent.git
    dest: /root/gather-agent
    version: "{{ gather_agent_branch }}"
    clone: yes

# git clone alert
- name: Git clone alert form github
  git:
    repo: https://{{ githubuser | urlencode }}:{{ githubpassword.user_input | urlencode | regex_replace('/', '%2F') | regex_replace('@', '%40') }}@github.com/{{ githubuser }}/alert.git
    dest: /root/kolla/docker/cloudalert/alert
    version: "{{ alert_branch }}"
    clone: yes

# git clone networking-ovn
- name: Git clone networking-ovn form github
  git:
    repo: https://{{ githubuser | urlencode }}:{{ githubpassword.user_input | urlencode | regex_replace('/', '%2F') | regex_replace('@', '%40') }}@github.com/{{ githubuser }}/networking-ovn.git
    dest: /root/networking-ovn
    version: "{{ networking_ovn_branch }}"
    clone: yes

# ensure build and wheels dirs exist
- name: Ensuer build and wheels dirs exist
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - "/root/gather-agent/build"
    - "/root/wheels"

# 创建  Makefile
- name: Create Makefile
  command: cmake .. 
  args:
    chdir: /root/gather-agent/build

# 编译采集器
- name: Compile gather-agent
  make:
    chdir: /root/gather-agent/build

# 准备networking-ovn的whl包
- name: Make wheel 
  command: pip wheel --wheel-dir=/root/wheels .
  args:
    chdir: /root/networking-ovn

# 打包wheel
- name: Compress wheels
  archive: 
    path: /root/wheels/networking_ovn-*.whl
    dest: /root/wheels/networking-ovn-ocata-wheel.tar.gz
    format: gz

# copy files to kolla
- name: Copy files to kolla
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "/root/public.tar", dest: "~/kolla/docker/cloudview/", mode: "0644" }
    - { src: "/root/pkg_middleware", dest: "~/kolla/docker/middleware/", mode: "0755" }
    - { src: "/root/gather-agent/build/agent", dest: "~/kolla/docker/gather/", mode: "0755" }
    - { src: "/root/wheels/networking-ovn-ocata-wheel.tar.gz", dest: "~/kolla/docker/neutron/neutron-server/", mode: "0644" }
