---
# Remove images
- name: Remove images
  shell: docker rmi $(docker images --format "{{'{'}}{{'{'}}.Repository{{'}'}}{{'}'}}:{{'{'}}{{'{'}}.Tag{{'}'}}{{'}'}}" | grep {{ namespace }})
  
# Remove centos:7 image
- name: Remove centos:7 image
  docker_image:
    name: centos:7
    state: absent

# Remove kolla-build.conf
- name: Remove kolla-build.conf
  file: 
    path: /etc/kolla/
    state: absent

# Pip uninstall tox
- name: Uninstall tox
  pip:
    name: tox
    state: absent

# Remove /opt/registry/docker directory
- name: Remove docker directory
  file: 
    path: /opt/registry/docker
    state: absent
