---
# copy Dockerfile to dest host
- name: Ensure kolla dockerfile exist
  copy:
    src: "{{ item }}"
    dest: /root/
  with_items:
    - "Dockerfile"
    - "nginx.repo"

# Git clone kolla-ansible
- name: Git clone kolla-ansible from Github
  git:
    repo: https://{{ githubuser | urlencode }}:{{ githubpassword.user_input | urlencode | regex_replace('/', '%2F') | regex_replace('@', '%40') }}@github.com/{{ githubuser }}/kolla-ansible.git
    dest: /root/kolla-ansible
    version: "{{ kolla_ansible_branch }}"
    clone: yes

# Git clone kolla_packages
- name: Git clone kolla_packages from Github
  git:
    repo: https://{{ githubuser | urlencode }}:{{ githubpassword.user_input | urlencode | regex_replace('/', '%2F') | regex_replace('@', '%40') }}@github.com/{{ githubuser }}/kolla_packages.git
    dest: /root/kolla_packages
    version: "{{ kolla_packages_branch }}"
    clone: yes
